--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.5

-- Started on 2025-10-28 16:30:19 CST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 17164)
-- Name: ecommerce; Type: SCHEMA; Schema: -; Owner: ecommerce_app
--

CREATE SCHEMA ecommerce;


ALTER SCHEMA ecommerce OWNER TO ecommerce_app;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 17257)
-- Name: cart_items; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.cart_items (
    id bigint NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL
);


ALTER TABLE ecommerce.cart_items OWNER TO ecommerce_app;

--
-- TOC entry 222 (class 1259 OID 17256)
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17263)
-- Name: carts; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.carts (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE ecommerce.carts OWNER TO ecommerce_app;

--
-- TOC entry 224 (class 1259 OID 17262)
-- Name: carts_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 17286)
-- Name: order_items; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.order_items (
    id bigint NOT NULL,
    line_total numeric(12,2) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE ecommerce.order_items OWNER TO ecommerce_app;

--
-- TOC entry 226 (class 1259 OID 17285)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17292)
-- Name: orders; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.orders (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delivery_due_date timestamp(6) with time zone NOT NULL,
    platform_fee numeric(12,2) NOT NULL,
    seller_amount numeric(12,2) NOT NULL,
    status character varying(255) DEFAULT 'PLACED'::character varying NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    buyer_id bigint NOT NULL,
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PLACED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


ALTER TABLE ecommerce.orders OWNER TO ecommerce_app;

--
-- TOC entry 228 (class 1259 OID 17291)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 17299)
-- Name: payments; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.payments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    brand character varying(255) NOT NULL,
    card_holder character varying(255) NOT NULL,
    card_id bigint,
    card_number character varying(19) NOT NULL,
    paid_at timestamp(6) with time zone NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE ecommerce.payments OWNER TO ecommerce_app;

--
-- TOC entry 230 (class 1259 OID 17298)
-- Name: payments_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17240)
-- Name: products; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.products (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    condition character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(255) NOT NULL,
    image_url character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(12,2) NOT NULL,
    status character varying(255) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT products_category_check CHECK (((category)::text = ANY ((ARRAY['TECHNOLOGY'::character varying, 'HOME'::character varying, 'ACADEMIC'::character varying, 'PERSONAL'::character varying, 'DECORATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT products_condition_check CHECK (((condition)::text = ANY ((ARRAY['NEW'::character varying, 'USED'::character varying])::text[]))),
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['IN_REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT products_stock_check CHECK ((stock >= 0))
);


ALTER TABLE ecommerce.products OWNER TO ecommerce_app;

--
-- TOC entry 220 (class 1259 OID 17239)
-- Name: products_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17307)
-- Name: saved_cards; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.saved_cards (
    id bigint NOT NULL,
    brand character varying(255) NOT NULL,
    card_holder character varying(255) NOT NULL,
    card_number character varying(19) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    exp_month integer,
    exp_year integer,
    label character varying(64),
    updated_at timestamp(6) with time zone NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE ecommerce.saved_cards OWNER TO ecommerce_app;

--
-- TOC entry 232 (class 1259 OID 17306)
-- Name: saved_cards_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.saved_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.saved_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 17186)
-- Name: users; Type: TABLE; Schema: ecommerce; Owner: ecommerce_app
--

CREATE TABLE ecommerce.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MODERATOR'::character varying, 'LOGISTICS'::character varying, 'COMMON'::character varying])::text[])))
);


ALTER TABLE ecommerce.users OWNER TO ecommerce_app;

--
-- TOC entry 218 (class 1259 OID 17185)
-- Name: users_id_seq; Type: SEQUENCE; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ecommerce.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ecommerce.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3608 (class 2606 OID 17261)
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3610 (class 2606 OID 17267)
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- TOC entry 3614 (class 2606 OID 17290)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 3616 (class 2606 OID 17297)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3618 (class 2606 OID 17305)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- TOC entry 3606 (class 2606 OID 17250)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 3622 (class 2606 OID 17313)
-- Name: saved_cards saved_cards_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.saved_cards
    ADD CONSTRAINT saved_cards_pkey PRIMARY KEY (id);


--
-- TOC entry 3612 (class 2606 OID 17269)
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- TOC entry 3602 (class 2606 OID 17195)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 3620 (class 2606 OID 17315)
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- TOC entry 3604 (class 2606 OID 17193)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3624 (class 2606 OID 17275)
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES ecommerce.products(id);


--
-- TOC entry 3630 (class 2606 OID 17331)
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES ecommerce.orders(id);


--
-- TOC entry 3626 (class 2606 OID 17280)
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES ecommerce.users(id);


--
-- TOC entry 3627 (class 2606 OID 17316)
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES ecommerce.orders(id);


--
-- TOC entry 3629 (class 2606 OID 17326)
-- Name: orders fkhtx3insd5ge6w486omk4fnk54; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.orders
    ADD CONSTRAINT fkhtx3insd5ge6w486omk4fnk54 FOREIGN KEY (buyer_id) REFERENCES ecommerce.users(id);


--
-- TOC entry 3631 (class 2606 OID 17336)
-- Name: saved_cards fkm20r4kly1nb2gya7gbg6t5x3y; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.saved_cards
    ADD CONSTRAINT fkm20r4kly1nb2gya7gbg6t5x3y FOREIGN KEY (owner_id) REFERENCES ecommerce.users(id);


--
-- TOC entry 3623 (class 2606 OID 17251)
-- Name: products fkmodgy1j6kai83i3mweyp731qc; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.products
    ADD CONSTRAINT fkmodgy1j6kai83i3mweyp731qc FOREIGN KEY (owner_id) REFERENCES ecommerce.users(id);


--
-- TOC entry 3628 (class 2606 OID 17321)
-- Name: order_items fkocimc7dtr037rh4ls4l95nlfi; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES ecommerce.products(id);


--
-- TOC entry 3625 (class 2606 OID 17270)
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: ecommerce; Owner: ecommerce_app
--

ALTER TABLE ONLY ecommerce.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES ecommerce.carts(id);


-- Completed on 2025-10-28 16:30:19 CST

--
-- PostgreSQL database dump complete
--

